### ISSUE TITLE
Join Community for a new unified format: Open GED

### ISSUE THREAD

**Issue by webysther** [gramps-project/Gramps.js#102]
I send the contributors an invite for a new project to move to a new truly Open Standard for GED, the [motivation](https://github.com/FamilySearch/GEDCOM/issues/198) and discussions for the [standard](https://github.com/openged/oged-specs/discussions/1).

**Comment by DavidMStraub** [comment]
@Nick-Hall FYI, but closing this as Gramps Web relies on importers/exporters from Gramps, so nothing to implement here.
