### ISSUE TITLE
Unable to setup development after following documentation. 

### ISSUE THREAD

**Issue by Airick73** [gramps-project/Gramps.js#108]
Hello,

First of all I wanted to thank the developers for this amazing open source genealogy app. I've ran it locally and I am very impressed with it. I wanted to be able to make some changes but I am unable to setup a development environment. To start I just wanted to edit frontend code. After following the steps listed here: https://gramps-project.github.io/web/dev-frontend/setup/ I ran into an error with Docker: 

" docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory')) " 

After troubleshooting the error, I was unable to run docker within gramps.js. This made me think I may also have to setup the backend development environment but I am not sure how I could run both simultaneously via docker. After looking through the GitHub I found this pull request in which someone suggested a way to make development easier by running both via Docker (if I understand it correctly): https://github.com/gramps-project/Gramps.js/pull/70 . I apologize if this issue was difficult to understand I tried to word it the best I could. Any insight from the community would be greatly appreciated so I can begin development of this wonderful app. 

Kindest Regards,
Eric

**Comment by DavidMStraub** [comment]
Hi Eric,

great that you want to contribute. In fact I updated the setup instructions very recently after #70 was merged, so it could well be that you are the first to discover an error in the docs or in the setup.

At which step do you get the error? Stackoverflow [seems to indicate](https://stackoverflow.com/questions/64952238/docker-errors-dockerexception-error-while-fetching-server-api-version) that this might be a docker setup issue.

Does `docker run hello-world` work?

**Comment by Airick73** [comment]
Hello David,

Thank you for the quick response. Here are the steps I took listed below. After attempting to run `docker run hello-world` I do get an error:

"docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?."

I've previously tried to run the command `systemctl start docker` listed in that Stackoverflow post but receive the error:

"System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down"

I was able to use docker successfully to deploy the gramps website according to these steps: https://gramps-project.github.io/web/Deployment/ . I am unsure if the error lies in docker or gramps.js. I will continue to troubleshoot the issue in the meantime but if you have any suggestions or were able to complete the steps successfully on your end, as always I appreciate your advice in this situation. 


![image](https://user-images.githubusercontent.com/72322466/192291121-eb21eb91-d67c-4e4a-b7c6-b8cd838c2cfe.png)

**Comment by Airick73** [comment]
Update: 
I was able to resolve the docker issue. After restarting my docker desktop app on windows I was able to successfully run the command `docker-compose up -d` .  (note: I am using Ubuntu Linux WSL)
![image](https://user-images.githubusercontent.com/72322466/192312038-299184dc-24b0-4fa2-9d86-1c22d9fb20bd.png)
However I was unable to load the app locally via local as I received an error: 
![image](https://user-images.githubusercontent.com/72322466/192312339-cdd120e8-421f-4101-a137-4ab432b303cf.png)
Checking my docker...the gramps-api-dev and gramps-proxy-dev container run without issue but the gramps-frontend-dev container will not run, giving the error:  
![image](https://user-images.githubusercontent.com/72322466/192313101-6e1e3cc1-ed4c-4987-95f9-46dd6d3dcd80.png)
![image](https://user-images.githubusercontent.com/72322466/192313171-7dab9fc0-6cd5-472b-b285-044114e44d5a.png)
I will continue to troubleshoot this issue but I thought it best to update the post as soon as I could in the meantime.

**Comment by DavidMStraub** [comment]
There is definitely something wrong with the current development setup but I wasn't able to fix it yet.

**Comment by DavidMStraub** [comment]
Ok I think I've found the issue and fixed it in bbebdf801170e02589b8227a97d45cc8f10535ac. The `node_modules` folder generated during build time was overwritten by the local mount.

Can you please check if it works now with the code in `main`?

**Comment by Airick73** [comment]
I removed all related files in VS code and docker. Following the steps listed here again: https://gramps-project.github.io/web/dev-frontend/setup/ 
I was successfully able to edit the frontend code and see the changes made in http://localhost:5555
![image](https://user-images.githubusercontent.com/72322466/192792365-5ca86d92-46ac-4136-a838-42d5ebc42dcd.png)
