### ISSUE TITLE
Add fonts to resources

### ISSUE THREAD

**Issue by skaa** [gramps-project/Gramps.js#111]
Can you use fonts as site resource? To not link it from google servers. It would be good for selfhosted site.

**Comment by DavidMStraub** [comment]
Yes, good point.

I was anyway planning to switch from Roboto to Inter, so let's consider that in one go.

**Comment by DavidMStraub** [comment]
I started implementing this but encountered the following challenges:

- After replacing Roboto by Inter, I also wanted to get rid of Roboto Slab. I tried Zilla Slab, which looks good, but it doesn't have cyrillic and Greek, so it would look bad even for these European languages
- There is still a dependency on the Google Material Icons font. The solution, I suppose, is to use [MDI](https://www.npmjs.com/package/@mdi/js) for all icons, but this will be quite some work.

**Comment by DavidMStraub** [comment]
Ended up bundling Roboto Slab and the Material Icon font as well for the moment.
