### ISSUE TITLE
Add new person birth date select bug

### ISSUE THREAD

**Issue by Airick73** [gramps-project/Gramps.js#112]
I was attempting to add a new person and enter their birth date via the add a new person tab but I was unable to enter a valid date. After entering the month and day, my next key stroke for year seems to reset the input field.
![image](https://user-images.githubusercontent.com/72322466/193411699-6c70e1f1-b0a7-4586-92de-1e425367068e.png)
![image](https://user-images.githubusercontent.com/72322466/193411740-d975eed1-110e-4050-9ba2-3edd5893e3cb.png)
After some trial and error I managed to input a date by first selecting the year and inputting a year then entering a month and day. 
![image](https://user-images.githubusercontent.com/72322466/193411798-4d82c931-9845-44e8-9a66-a425bbd88a16.png)
![image](https://user-images.githubusercontent.com/72322466/193411815-1aed6dda-ead0-4aae-bff2-cce4ff49b704.png)
I am not sure what is causing this issue but I thought I would bring it to attention. If I am able to resolve this bug in the meantime I will add that information to this issue. 

Best,
Eric

**Comment by DavidMStraub** [comment]
Hi, that's strange. Which browser are you using? Normally, the browser should be showing its native date select widget.

**Comment by Airick73** [comment]
I'm using chrome but I was able to replicate the issue in edge.

**Comment by DavidMStraub** [comment]
Ok, I can confirm the problem.

I also realized only now that Chrome Desktop doesn't open the date picker automatically. Firefox on Desktop and Chrome on Android do. For Chrome on Desktop I have to press space or enter to open it. Can you confirm that? How is it for Edge? (Related: https://github.com/material-components/material-web/issues/1715)

**Comment by DavidMStraub** [comment]
Can you please check whether the last commit fixes the issue for you?

**Comment by Airick73** [comment]
Thank you getting back to me on this issue. I was able to access the native date picker after pressing space on both Chrome and Edge.
