### ISSUE TITLE
Login not possible without search index

### ISSUE THREAD

**Issue by cdhorn** [gramps-project/Gramps.js#12]
It is not possible to login if the search index is not available as selection of a home person is mandatory.

**Comment by Zauberstuhl** [comment]
I had the same problem. Execute to build the index:

`python3 -m gramps_webapi --config config/config.cfg search index-full`

**Comment by DavidMStraub** [comment]
It's true, and there are more and more parts of the app relying on the search index, so I don't think we should work around a missing search index. But it should definitely be documented better.

**Comment by DavidMStraub** [comment]
I'm going to close this as the new Gramps Web images build the search index automatically on first run.
