### ISSUE TITLE
Cannot reopen modal window if closed by Esc

### ISSUE THREAD

**Issue by fuelen** [gramps-project/Gramps.js#135]
When I edit something, that opens a modal window, press Esc, so the window is closed, then I cannot reopen it.

**Comment by DavidMStraub** [comment]
Yes, true.  A workaround is to exit and reenter edit mode.

**Comment by DavidMStraub** [comment]
Turned out to be easy to fix.

Please don't get used to this speed of solving bugs :laughing:
