### ISSUE TITLE
Number of generations slider is not visible

### ISSUE THREAD

**Issue by fuelen** [gramps-project/Gramps.js#138]
![зображення](https://user-images.githubusercontent.com/588762/203148987-84ea1caa-ce72-4030-8b19-32ceb83ef833.png)

**Comment by kombatt** [comment]
issue present in horizontal tree view

**Comment by DavidMStraub** [comment]
Likely related to #133

**Comment by fuelen** [comment]
Slider is wrapped into span with class `mdc-deprecated-list-item__text` and that's why it has small size 48x48.

**Comment by DavidMStraub** [comment]
I think the best solution is to just use the +/- buttons from the vertical tree view. Sliders are anyway not great for changing stuff by small amounts.
