### ISSUE TITLE
Saving an empty event breaks family page

### ISSUE THREAD

**Issue by fuelen** [gramps-project/Gramps.js#139]
Steps to reproduce
* Go to family page
* Edit Family
* Go to Events tab
* Click Share an existing event icon
* Don't touch fields in the form
* Click Save button
* Refreshing a page shows blank page and 500 error in the toaster

**Comment by DavidMStraub** [comment]
I'm a bit puzzled why `GrampsjsObjectForm` doesn't disable the save button if `this.isFormValid` is false, like `GrampsjsViewNew...` does. That's an omission. But once we add it, I suspect lots of forms will break as they are currently not implementing form validation properly.
