### ISSUE TITLE
Uploading a big file returns 404

### ISSUE THREAD

**Issue by fuelen** [gramps-project/Gramps.js#142]
I tried to upload 2MB video file and got a toaster with the 404 error.
This is both, client and server error. Client should show proper error when the file is too big.

Server logs:
```
gramps-proxy-dev     | 2022/11/21 20:49:17 [error] 28#28: *26935 client intended to send too large body: 2130794 bytes, client: 172.23.0.1, server: , request: "POST /api/media/ HTTP/1.1", host: "localhost:5555", referrer: "http://localhost:5555/new_media"
gramps-proxy-dev     | [21/Nov/2022:20:49:17 +0000] 413 POST /api/media/ HTTP/1.1 - - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
gramps-proxy-dev     | [21/Nov/2022:20:49:17 +0000] 404 PUT /api/media/undefined HTTP/1.1 - 172.23.0.4:5000 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
gramps-proxy-dev     | [21/Nov/2022:20:49:25 +0000] 101 GET /wds HTTP/1.1 - 172.23.0.3:8000 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
```
How can I configure a limit for file size?

**Comment by DavidMStraub** [comment]
This is using the development docker-compose file in the root of the repository?

Can you try adding `client_max_body_size 500m;` to `dev/nginx.conf`?

**Comment by fuelen** [comment]
yes, I use development docker-compose file. Adding `client_max_body_size 500m;` helped

**Comment by DavidMStraub** [comment]
Ok great we should add this.

I also noticed that this is missing for the base Gramps Web image.

**Comment by DavidMStraub** [comment]
Added to the dev image configuration and to the deployment docs (https://github.com/gramps-project/web/commit/8069772c41bbce42d1c9aaf2b2325c60d1326db3).
