### ISSUE TITLE
Edit type for place and events

### ISSUE THREAD

**Issue by fuelen** [gramps-project/Gramps.js#146]
As for now, I can create an event with some type, but after creation I cannot longer update its type

**Comment by pflodo** [comment]
This is the same for Places - it is not just the type, but Name, Hierarchy, sources etc.

**Comment by DavidMStraub** [comment]
The place hierarchy (in the sence of parent places) can be changed, but I just noticed there is a bug that the add parent place button is not shown if the place doesn't have a parent yet.

The primary place name can be changed. Sources as well.
