### ISSUE TITLE
Serve pages from path other than root

### ISSUE THREAD

**Issue by StephenAdams-hamont** [gramps-project/Gramps.js#154]
Using the default docker installation pages will serve from the domain root. I have other services sharing port 80 through nginx using the VIRTUAL_PATH keyword. How can I modify my container to serve pages from a path other than /?

**Comment by DavidMStraub** [comment]
We had that option initally, but it caused a huge amount of issues so it was eventually removed. My recommendation would be to use a separate subdomain. (I am also hosting multiple services on the same service at port 443.)

**Comment by DavidMStraub** [comment]
Closing this as wontfix, but if someone wants to take responsibility of implementing and maintaining this feature, I am not opposed.
