### ISSUE TITLE
Calendar widget for date selector not popping up in Add New Media Screen

### ISSUE THREAD

**Issue by StephenAdams-hamont** [gramps-project/Gramps.js#156]
After uploading a file in add new media I select a regular date and the calendar icon is unresponsive. It appears as an icon only. Manual entry of the date is functional.

**Comment by DavidMStraub** [comment]
I suspect this is the same issue as #112. Can you try pressing space? For some reason, Chrome on desktop doesn't open the data picker in an input type=date field when you click on it, only once you press space. It works on Firefox and on mobile Chrome.

**Comment by DavidMStraub** [comment]
I just learned [`showPicker()`](about https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/showPicker) which might help but I anyway plan to refactor the date picker UI due to #160.
