### ISSUE TITLE
Docker image can’t be found 

### ISSUE THREAD

**Issue by DZ65367709** [gramps-project/Gramps.js#158]
In the document of instruction, we were told the convenient deployment was use a docker image. But   It seems like the docker image doesn’t exist…in hub.docker.com. Would you post it again? If so when it will be shown? Thank you for your response.

**Comment by DavidMStraub** [comment]
Please see https://gramps-project.github.io/web/ for detailed docker deployment instructions.

**Comment by DZ65367709** [comment]
I am a beginner and want to learn to use gramps, but I don't know how to install it, and I am very confused: if to achieve all the functions from the front end to the back end, which software should be installed?  Or which softwares combination should be installed?  Or if all your softwares should be installed to achieve it?  I didn't find any description of this in your documentation.
I installed Ubuntu in a Docker, I want to deploy gramps(solo? or a combination? whatever to fulfill the functions) in Ubuntu. I studied several days and have no idea how to do this… please help.

**Comment by DavidMStraub** [comment]
Sorry, but I can't help you this way.

I sent you the link to the documentation which has description in steps: https://gramps-project.github.io/web/Deployment/

Please follow those steps and if anything does not work, ask for help.

If you are not experienced with Docker, it might also make more sense to use the 1-click app: https://gramps-project.github.io/web/DigitalOcean/

By the way, please use [the Gramps forum](https://gramps.discourse.group/) for general support requests, as thi is apparently not an issue with the software as such.
