### ISSUE TITLE
Error while running docker-compose

### ISSUE THREAD

**Issue by DallanQ** [gramps-project/Gramps.js#182]
I got caught up on some other projects and thought I would play around with GrampsWeb today. I can get the [quickstart](https://gramps-project.github.io/web/quickstart/) working fine, but when I try to execute the [docker-compose file](https://raw.githubusercontent.com/gramps-project/web/main/examples/docker-compose-base/docker-compose.yml) from Step 1 using

    docker-compose up -d

I receive the following error:

````
Creating network "gramps_default" with the default driver
Creating grampsweb_redis ... done
Creating gramps_grampsweb_1 ... 
Creating grampsweb_celery   ... 
Creating grampsweb_celery   ... error

ERROR: for grampsweb_celery  Cannot start service grampsweb_celery: driver failed programming externalCreating gramps_grampsweb_1 ... done
e50d7c): Bind for 0.0.0.0:80 failed: port is already allocated

ERROR: for grampsweb_celery  Cannot start service grampsweb_celery: driver failed programming external connectivity on endpoint grampsweb_celery (0bdf236152c78e5677d6bb466c7fcd558f745b9c031b4334cbbac61635e50d7c): Bind for 0.0.0.0:80 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
````

Before running "docker-compose up" and after running "docker-compose down", nothing is listening on port 80. 

Is it trying to create the grampsweb_celery service twice?  I haven't seen this syntax in a docker file before:

    grampsweb_celery:
        <<: *grampsweb  # YAML merge key copying the entire grampsweb service config

Any ideas what's going wrong? I'm running this on PopOS (based on Ubuntu) 22.04 LTS . Thank you for your help!

**Comment by DavidMStraub** [comment]
Thanks for spotting it, I updated the docs  just the day before and an error must have slipped in.

The syntax is not docker compose specific but a YAML feature to reuse part of a mapping. I suspect the problem is that the LETSENCRYPT_... env vars shouldn't be set on the celery service. Will look into it later.

**Comment by DavidMStraub** [comment]
@DallanQ, can you try if adding

```
  ports: []
```

to the celery service fixes it?

**Comment by DallanQ** [comment]
That did it. Thanks!
