### ISSUE TITLE
Translation not pulled in

### ISSUE THREAD

**Issue by MedicMomcilo** [gramps-project/Gramps.js#191]
Hello! :slightly_smiling_face: 

Either I'm doing something wrong or the translations aren't pulled in correctly.
(At least Serbian doesn't seem to be).

Here is the screenshot displaying many untranslated strings, while there are none in Weblate:
(Also visible in the screenshot is the sha256 of the image, confirming I'm using latest one)
![image](https://user-images.githubusercontent.com/7031596/226425310-58376cb2-5010-496f-91ad-7b038700ca0e.png)

Please let me know if there is anything I can do to help further progress this.

Kind regards,
Momo.

**Comment by DavidMStraub** [comment]
Oh dear, I noticed that we should have added every new language to `src/lang/index.js`, which wasn't done, so the translations were unused for no less than 37 languages!! Incredible that none of the other translators had complained so far... thanks for catching!

**Comment by MedicMomcilo** [comment]
Thanks David for quick resolution!

Even though it is much much better now, there are still some oddities.
My guess is that you rely on some of the Gramps translations as well?

There are untranslated strings in the interface that are not in Weblate (blue).
Also, there are translated strings that are not part of gramps-web in Weblate (red).

![Screenshot from 2023-03-21 07-43-34](https://user-images.githubusercontent.com/7031596/226535612-903d1d1a-5802-472f-9b75-3886cea72d2f.png)


Please let me know if I should focus on translating gramps project to get these in?

Kind regards,
Momo.

**Comment by DavidMStraub** [comment]
Exactly, all strings that exist in Gramps (desktop) are taken from there, so your screenshot means that these strings are not translated in Gramps 5.1.5. If they are translated in Weblate already, we have to wait for the next Gramps release for it to appear in the default Docker image.
