### ISSUE TITLE
Can't effectively modify or delete a lot of things in this UI

### ISSUE THREAD

**Issue by Leopere** [gramps-project/Gramps.js#204]
Things like modifying family's and adding step parents and such of the sort is either extremely difficult or impossible.

**Comment by DavidMStraub** [comment]
What about looking for existing issues and feature requests? Also extremely difficult?

Sorry, but this kind of feedback is not useful.

You want to have "a lot of things". Well, wait or help.

**Comment by Leopere** [comment]
I guess I'm looking for feedback as to if this project is still moving and your fast response answered that fairly effectively.

**Comment by DavidMStraub** [comment]
Seriously? If that's what you are after, look at the commit log or the contribution graph rather than bothering me with discrespectful comments in my free time. Thanks.
