### ISSUE TITLE
Export fails and it only downloads a html file

### ISSUE THREAD

**Issue by MegaThorx** [gramps-project/Gramps.js#212]
When I try to export it in any format it fails with the following error. The frontend starts the download of a html file and does not check the error which is returned. The API call fails with a 401 error.

```
gramps-grampsweb-1  | Unable to init server: Could not connect: Connection refused
gramps-grampsweb-1  | Unable to init server: Could not connect: Connection refused
gramps-grampsweb-1  | 
gramps-grampsweb-1  | (gunicorn:18): Gtk-CRITICAL **: 13:13:16.368: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
gramps-grampsweb-1  | Unable to init server: Could not connect: Connection refused
```

sometimes it includes

```
gramps-grampsweb-1  | ERROR:root:Error parsing list of recent DBs from file /root/.gramps/recent-files-gramps.xml: no element found: line 1, column 0.
gramps-grampsweb-1  | This might indicate a damage to your files.
gramps-grampsweb-1  | If you're sure there is no problem with other files, delete it, and restart Gramps.
```

**Comment by DavidMStraub** [comment]
Or actually both frontend and backend :man_facepalming:

**Comment by DavidMStraub** [comment]
... and there might be a third issue: please make sure you have this volume shared between flask and celery:

https://github.com/gramps-project/web/commit/001d1080fb018ec47db7ad1b3244f5843b982e3f

**Comment by MegaThorx** [comment]
It works now for me. I've added the volume `/app/cache` and changed the image to `latest-devel` (for now).
