### ISSUE TITLE
grampsweb does not initialize correctly on install…

### ISSUE THREAD

**Issue by dmgursky** [gramps-project/Gramps.js#235]
I am setting up a second grampsweb server on my home intranet.  As the nodes on this local network are isolated from the Internet writ large, I did a “vanilla” install, viz the 1-Click install on Digital Ocean, although I believe the issue is there as well.

HW / SW is a Raspberry Pi 4 w/ the latest Raspbian release.  Docker and Docker-Compose manually installed (apt install docker docker-compose).  No updates otherwise.

I created /opt/grampsweb, the docker-compose.y’all within that directory:

`
version: "3.3”

services:
  grampsweb: &grampsweb
    image: [ghcr.io/gramps-project/grampsweb:latest](http://ghcr.io/gramps-project/grampsweb:latest)
    restart: always
    ports:
      - "8000:5000"  # host:docker
    environment:
      GRAMPSWEB_TREE: "Gramps Web"  # will create a new tree if not exists
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
    depends_on:
      - grampsweb_redis
    volumes:
      - gramps_users:/app/users  # persist user database
      - gramps_index:/app/indexdir  # persist search index
      - gramps_thumb_cache:/app/thumbnail_cache  # persist thumbnails
      - gramps_cache:/app/cache  # persist export and report caches
      - gramps_secret:/app/secret  # persist flask secret
      - gramps_db:/root/.gramps/grampsdb  # persist Gramps database
      - gramps_media:/app/media  # persist media files
      - gramps_tmp:/tmp

  grampsweb_celery:
    <<: *grampsweb  # YAML merge key copying the entire grampsweb service config
    ports: []
    container_name: grampsweb_celery
    depends_on:
      - grampsweb_redis
    command: celery -A gramps_webapi.celery worker --loglevel=INFO

  grampsweb_redis:
    image: redis:alpine
    container_name: grampsweb_redis
    restart: always

volumes:
  gramps_users:
  gramps_index:
  gramps_thumb_cache:
  gramps_cache:
  gramps_secret:
  gramps_db:
  gramps_media:
  gramps_tmp:
`

When I start grampsweb initial, firstrun.sh and .py are NOT created, and when you open the site, you go to the username/password screen, not the firstlogin page….

**Comment by dmgursky** [comment]
Duly noted WRT firstrun.sh and py.

frontend, backend, it’s affecting my end! 🤣

**Comment by DavidMStraub** [comment]
Fixed by https://github.com/gramps-project/Gramps.js/commit/fcc3f12053245be9db685d367a93959f7a3938c4.

**Comment by dmgursky** [comment]
I affirm the software is fixed and is operating correctly WRT the issue as described.
