### ISSUE TITLE
Add Descendant Tree view

### ISSUE THREAD

**Issue by OJ7** [gramps-project/Gramps.js#236]
I updated my gramps instance (after a long time) and noticed that the family tree view does not include descendants anymore (only ancestors). Would it be difficult to add that option back in?

**Comment by DavidMStraub** [comment]
That would be a weird new feature 🤔 

Seriously, nothing changed in this respect.

**Comment by DavidMStraub** [comment]
Sorry, misread your question at first.

The tree views were completely reimplemented from scratch based on D3.js in [v0.19](https://github.com/gramps-project/Gramps.js/releases/tag/v0.19.0). Indeed, this does not include an hourglass graph. I currently have other priorities, but a contribution would be welcome. The D3.js based graphs have a huge potential.

**Comment by bahuma20** [comment]
Just want to throw an idea into the room:

Is it maybe possible to have two trees? One for ancestors and one for decendents and display them on top of each other?
