### ISSUE TITLE
Can't register due to error

### ISSUE THREAD

**Issue by dsoprea** [gramps-project/Gramps.js#261]
![image](https://github.com/gramps-project/Gramps.js/assets/715626/b1c3c6a5-c0f1-4b9c-9791-152f99bee727)

**Comment by DavidMStraub** [comment]
Right. In the new multi-tree setup, the normal registration page doesn't work as the server doesn't know which tree to register to. So the link on the login page needs to be hidden; instead, each tree has a dedicated registration link that tree owners can share.

**Comment by dsoprea** [comment]
Looking forward to hear about next steps. 

The naive interpretation of your response implies that you can't get on the system unless you already have a tree on the system. The naive user would assume that there must be some landing page that transcends this, or at least default tree that exists for the sake of bootstrapping users while keeping with the tree paradigm.

**Comment by DavidMStraub** [comment]
Updated the docs and added a sharable registration link in 360b6dc69bb25d77dc4d0d55ecf7b69c8fffcb3f.

>  The naive user would assume that there must be some landing page that transcends this, or at least default tree that exists for the sake of bootstrapping users while keeping with the tree paradigm.

No, there is no default tree. Since user accounts are always tied to trees, it is not possible to register without knowing the tree.

**Comment by dsoprea** [comment]
Has this been deployed? Is there a different course of action required on my part, or should the previous process now complete?

**Comment by DavidMStraub** [comment]
It has been released in Gramps.js v23.8.2, which has already been deployed at Grampshub (if that's what you're using). For the process, please see [the docs](https://www.grampsweb.org/user-guide/registration/).
