### ISSUE TITLE
No login link on mobile

### ISSUE THREAD

**Issue by dsoprea** [gramps-project/Gramps.js#267]
![image](https://github.com/gramps-project/Gramps.js/assets/715626/b9092123-9b2a-4243-871e-8d89df694578)

![image](https://github.com/gramps-project/Gramps.js/assets/715626/9ee07e07-b4f6-4396-8377-5d73d14a9374)

**Comment by DavidMStraub** [comment]
Oops, thanks. Closing as it's not a Gramps.js issue, but will fix it.

**Comment by dsoprea** [comment]
Which is the relevant project?

**Comment by DavidMStraub** [comment]
There is no public Github repo for the Grampshub web site...

**Comment by dsoprea** [comment]
Is there any way that you can add a logout link, too?
