### ISSUE TITLE
Ancestor Tree goes out of bounds when >6 generations

### ISSUE THREAD

**Issue by emiltmadsen** [gramps-project/Gramps.js#277]
![Screenshot 2023-09-05 021000](https://github.com/gramps-project/Gramps.js/assets/61865338/83a34e93-52f5-4084-beb7-f4b369aee4da)

As seen on the screenshot, when you choose 6 or more generations the tree goes out of view.

**Comment by DavidMStraub** [comment]
Right.

@digitaltembo, would be be willing to take a look at this, as you contributed the most recent improvement?
