### ISSUE TITLE
The UI allows to create a Span without end date, which results in corrupted event data in the database

### ISSUE THREAD

**Issue by elnigno** [gramps-project/Gramps.js#282]
- Create a new event for a certain individual
- Set the date of the event to Span, and only set the first date
- Save
- Try to load the event from the events list
- You'll get an error 500

The errors occurs in both Gramps Web and Gramps Desktop, however Gramps Desktop shows a validation error when trying to save a Span with no end date.

It took me a while to track down the problem and recover the event, which also made many related entities inaccessible in Gramps Web and Desktop. I ended up exporting the data base with the SQL Export addon, correcting the data there, then importing it back with the SQL Import addon.

There should be a validation error in Gramps Web when creating invalid dates.
Alternatively add support for open Span, but that's not specific to the web version.
Another nice thing would be to consider adding a db check to find and possibly fix wrong dates.

**Comment by DavidMStraub** [comment]
Thanks for reporting! Open span will be added soon in Gramps 5.2, but in this case it is in fact a frontend bug and indeed we have to prevent saving the form with invalid date, because Gramps itself (the library) doesn't prevent it.

**Comment by elnigno** [comment]
Thanks for the reply, and glad to hear open spans are coming with 5.2!

**Comment by DavidMStraub** [comment]
We need to add an isValid method like here d567a8f6515f2cc49d18ff908df30981744aee1e to all forms with dates.
