### ISSUE TITLE
Person name does not show suffix 

### ISSUE THREAD

**Issue by Rick603** [gramps-project/Gramps.js#284]
Is this a bug or a feature (or an enhancement)? It seems that the surname suffix is not being displayed where I expect it to be visible in the GrampsWeb UI as presented on GrampsHub. It is not at the top of the People viewer/editor, not in the Ancestor Tree, not in the Fan Chart, and it would be nice to have it displayed in the People List. Please see the attached file for examples of what I am talking about. 

I just noticed that in the Gramps Fan Chart, the suffix follows the Given name, whereas in most other scenarios, it follows the Surname. Guess I should put that issue in over on that bug tracker.

[GrampsWebSuffixIssue.pdf](https://github.com/gramps-project/Gramps.js/files/12705526/GrampsWebSuffixIssue.pdf)

**Comment by DavidMStraub** [comment]
No, it's not a feature.

It needs to be fixed in Gramps Web API, so I will open an issue there.
