### ISSUE TITLE
Size of media objects is broken in admin user interface

### ISSUE THREAD

**Issue by hartenthaler** [gramps-project/Gramps.js#299]
The size of all media files is shown in the admin user interface as "0% ( NaN undefinedB / 10.0 GB )". I assume that "NaN undefinedB" should have a value.

**Comment by hartenthaler** [comment]
Gramps 5.1.5
Gramps Web API 1.3.2
Gramps.js 23.10.2
locale: en
multi-tree: true
task queue: true

**Comment by DavidMStraub** [comment]
Ok, that was an easy one :wink: Should be fixed in the next release.
