### ISSUE TITLE
It would be nice, if you could zoom and pan the tree- and fancharts

### ISSUE THREAD

**Issue by geostag** [gramps-project/Gramps.js#316]
The ability of zooming and panning the charts would make it more convenient when viewing large charts

**Comment by DavidMStraub** [comment]
Implemented in #317.

I am testing the merged version on mobile now and getting some inconsistencies (Chrome on Android):

![Screenshot_20231127_111358_Chrome.jpg](https://github.com/gramps-project/Gramps.js/assets/10965193/0e22c95f-5be5-4ab3-9238-bb50eaa26bca)
