### ISSUE TITLE
Error 404 toaster after the first run

### ISSUE THREAD

**Issue by fuelen** [gramps-project/Gramps.js#324]
I didn't specify a tree to upload during the first run. I was successfully logged in, and after each page refresh I see 404 error in a toaster.
From the Network tab, the following path responds with 404: `/api/people/?gramps_id=I0000&profile=self&extend=media_list`

**Comment by fuelen** [comment]
Yes, this is the case. This error is absent if I log in using incognito mode

**Comment by DavidMStraub** [comment]
I will go ahead and close this issue - I don't see how we can avoid it, and it will go away when a new home person is set.
