### ISSUE TITLE
Accedental removal of admin role

### ISSUE THREAD

**Issue by ItsSiem** [gramps-project/Gramps.js#354]
It's possible for the site admin to assign themself a different role, and loose admin rights. I've personally done this on accident, I managed to just go in the db and assign myself the admin role again. 

I think this would be mitigated by showing the admin role in the role selection drop down, or at least show that a user has the admin role. Currently the field just remains blank.

Blank role field:
![image](https://github.com/gramps-project/Gramps.js/assets/47294812/ce530508-1f08-490e-aab0-bfbcc1340410)

Admin role is not available in the drop down:
![image](https://github.com/gramps-project/Gramps.js/assets/47294812/cc7c5719-1bc4-46b8-ad03-e0e430aae560)

It's honestly not a big deal, because the admin role does not have that much more capabilities than the owner role. It's mostly multi tree stuff. But I thought I'd share it anyway at least to just document that this is an issue people could have.

**Comment by DavidMStraub** [comment]
Thanks, let's use this issue for the missing Admin entry in the dropdown. If we want to prevent admins/owners from locking themselves out, that would have to be handled in https://github.com/gramps-project/gramps-webapi/, but not sure we should.
