### ISSUE TITLE
Expand Tree View

### ISSUE THREAD

**Issue by lucaberti** [gramps-project/Gramps.js#358]
Hello, I think Gramps interface would greatly benefit of a  tree-view overhoul. Currently it displays just the ascending legagy. It would be a game changer if it could also display the "descending" tree (sons/grandsons and so on) as well as the "lateral" tree (brothers and sisters).

**Comment by DavidMStraub** [comment]
Did you try clicking "descendant tree"? Might be a game changer :wink"

The "lateral" tree feature is tracked here: #313

**Comment by lucaberti** [comment]
That could be ;) Where is that?
![Immagine 2024-01-17 142755](https://github.com/gramps-project/Gramps.js/assets/18533461/47746add-ab90-4716-961b-e274cc23a122)

**Comment by lucaberti** [comment]
Uhm, I used the docker compose file listed on the websit: 
image: ghcr.io/gramps-project/grampsweb:latest
What I did wrong?

**Comment by lucaberti** [comment]
> Just pull the latest version. Or refresh your browser...
> 
> Please share the version info from settings/administration (unless your version is so old that you don't see it...)

Sorry, I forgot to mention that I installed the docker image three days ago. 

Version info:
Gramps 5.1.5
Gramps Web API 1.3.0
Gramps.js 23.9.2

**Comment by DavidMStraub** [comment]
The current versions are
Gramps 5.1.5 -> 5.1.6
Gramps Web API 1.3.0 -> 1.5.0
Gramps.js 23.9.2 -> 24.1.0

Just do `docker pull ghcr.io/gramps-project/grampsweb:latest`.

**Comment by lucaberti** [comment]
Thank you for the help. The command did not really helped tough, since to update the container I had to detach it and rebuild. And since it was installed with docker compose (on a QNAP nas) I finally had to redo everything form the beginning. Furnutatelly I did not worked too much on the tree I imported from MyHerigate...

**Comment by DavidMStraub** [comment]
> The command did not really helped tough, since to update the container I had to detach it and rebuild. And since it was installed with docker compose (on a QNAP nas) I finally had to redo everything form the beginning. 

In docker-compose, you just do `docker-compose pull && docker-compose up -d`. But it all has nothing to do with Gramps Web really, so I think this is not the right place to discuss.
