### ISSUE TITLE
Map Overlay Images - allow rotation of image

### ISSUE THREAD

**Issue by brucejackson** [gramps-project/Gramps.js#66]
I like the ability to overlay an image over a map directly in GrampsWeb.  I have been doing it in Google Earth.  It would be nice if there is a means to rotate this image to match the underlying map.

Historic Map overlayed in Google Earth
![image](https://user-images.githubusercontent.com/1219029/147503027-182da400-06f7-4e6d-808b-011329b7876e.png)

The same Historic Map overlayed in GrampsWeb
![image](https://user-images.githubusercontent.com/1219029/147503158-64a38ade-6d79-4bd0-af8c-6438b651cce8.png)

**Comment by DavidMStraub** [comment]
I understand but I'd like to avoid that as it would complicate the UI and the storage of the transformation. I think there is a tradeoff between editing a graphic and being able to manipulate it in the UI. Orienting a map by rotating it is something that is very simple in a graphic editor. In practice, I have anyway often found the need to edit images before using them as a map overlay, e.g. to make the blank part in your map transparent.

**Comment by DavidMStraub** [comment]
Closing this for now due to the above arguments.
