### ISSUE TITLE
Use Notes for Blog instead of Sources

### ISSUE THREAD

**Issue by Wdavery** [gramps-project/Gramps.js#73]
From an organization standpoint, why was Sources chosen as the repository for blog posts over Notes?
Is it solely because there is separate "Title" entry for them?
 
It seems to me like a strange place to store them, especially as the Source Title = Blog Title so they end up scattered among your regular sources. 

Could be `Notes tagged as Blog`, or `Notes with type "Blog"`?

Even a singular "Blog" source, where citations are individual posts would make more sense to me. Maybe I'm alone in this, or looking at the wrong way, so forgive me if so.

**Comment by DavidMStraub** [comment]
Hi, the Note *is* actually the repository for the *text* of the blog posts. For the entire blog posts, it's not just the missing author field, but much more importantly the missing media objects. What I was looking for is a container object holding both text and images.

Also from a genealogical standpoint, in my opinion it fits quite well: the posts I write on my own blog typically contain some anecdotes or other secondary information that might not always be contained in other sources in Gramps. So IMO it makes perfect sense to treat each blog post as a source. In my case, I have a repository that corresponds to my Gramps Web instance and all blog posts are sources inside that repository.

**Comment by Wdavery** [comment]
Thanks for your answer David!
As I was exploring gramps-web I totally forgot about repositories as a level-above organization tool. 

Media was also an oversight for me. 
With this in mind I will continue experimenting with blog posts and how they will work for me. 

Also, thanks for your work on this project—it's really a dream come true!
