### ISSUE TITLE
Keyboard shortcuts interfere with text input

### ISSUE THREAD

**Issue by windmark** [gramps-project/Gramps.js#80]
First of all, thanks for all the great work on this!

I’m running into the issue that keyboard shortcuts interfere with text input, making it impossible to write certain characters. 

- g - since it expects a second character for the shortcut activation 
- s - since it opens search 
  - also there isn’t any way to close it on mobile
- ? 
  - there also is no way to close this modal on mobile

I see this was addressed in #74, but my issue happens for example in the Notes text field.

This happens on iOS and since I’m without a laptop I unfortunately can’t check on desktop. On mobile I would almost say keyboard shortcuts can be turned off fully. 

I’m running the latest versions of both api and Gramps.js

**Comment by DavidMStraub** [comment]
Thanks, you're right, I can even reproduce it on desktop. My last commit hopefully fixed it!

**Comment by windmark** [comment]
Great! I tested out the new version and I can confirm this issue is now fixed.
